apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: code-server
spec:
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: code-server
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: code-server
  valuesFrom:
    - kind: ConfigMap
      name: code-server-helm-chart-value-overrides
      valuesKey: values.yaml
