apiVersion: v1
kind: ConfigMap
metadata:
  name: overseerr-helm-chart-value-overrides
  namespace: overseerr
data:
  values.yaml: |-
    #
    # IMPORTANT NOTE
    #
    # This chart inherits from our common library chart. You can check the default values/options here:
    # https://github.com/geek-cookbook/library-charts/tree/main/charts/stable/common/values.yaml
    #

    image:
      # -- image repository
      repository: ghcr.io/sct/overseerr
      # -- image tag
      tag: 1.32.5
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: UTC
      # -- Set the application log level
      LOG_LEVEL: info

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 5055

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        hosts:
          - host: overseerr.henabytes.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: letsencrypt-wildcard-cert-henabytes.com-staging
            hosts:
              - overseerr.henabytes.com

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: true
        storageClass: ceph-block
        mountPath: /app/config
