apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: overseerr
spec:
  chart:
    spec:
      chart: overseerr
      version: 5.x
      sourceRef:
        kind: HelmRepository
        name: geek-cookbook
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: overseerr
  valuesFrom:
    - kind: ConfigMap
      name: overseerr-helm-chart-value-overrides
      valuesKey: values.yaml # This is the default, but best to be explicit for clarity
