apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: henworth@henabytes.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - henabytes.com
        dns01:
          cloudflare:
            email: hennessy.michaelg@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
