apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: "mastodon.henabytes.com"
  namespace: mastodon
spec:
  endpoints:
    - dnsName: "mastodon.henabytes.com"
      recordTTL: 180
      recordType: CNAME
      targets:
        - "home.henabytes.com"
