apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mastodon-smtp-auth
  namespace: mastodon
spec:
  encryptedData:
    login: AgA3gGc9wZjbQ0JZ46ZLEAWms9gzt/4bcXpkI9BrvlOSSXdChSDv3BXcZ1e6XCmDPeKdDszNEiDd8haTk4aEAV+SPrNSePkoxiUP/tZQHiLYKAic5fU6MhBf5tLcydWDz5IPPCHICB9VZZAX4+yr7yoTe30lzn7pYFyJOohKQ2i4bJasSnKmJKGXlvwhUZijQ10i/7LAftF0rYAq1RRwDpxDl5ircYLevfEpL0s/VzHQClGMfXnKVNu11TJ+C5lsU3iKHyum+0xeXiC//FF/WK1tROgNrMP51EZqQUQViQbLC9IAkLgH1g1z69/fBqykYjt3oBuyRTLAMQrrw0NfiR37RzRS6XjwQ2Az6IGG+m70ciLK1Vu+LZMSrBFfVe82He52jWL1Upp6jWwOcUTNMoye78/xFWonGUY37wZcXR9Py/LrMvwnNwEC1OzFXdaxb4/Nq8BmX8eBq+VX2mChYPkbJNanmP0zgt3ZpAE2BnQO2YIUnKifKnr/AIw9JPsOuWFSkaqOvPZSEYQUmxmIL3nsNdeGRoBt/BcViHbkNrLizzjL8P9+T9RHlHcX14BFNj/ehee5oERB8/13azRESxgVT10astKGXFWXb8JL5b4KYhyuStlo1EzrQ3DVVmMyGmv8bpunHB+H2I/o+ZcjY61yBCj/3NpqTs4qgGex6Fe3b263xGhhnF7sw+82mqkxGcB9KTbbvfZwmzunPrckvY/WUSQ=
    password: AgCuakLWIwMC5ht8jFFCiegqZF7G7cO1xTzlnXyqZTi7PSxlhuSPo4w/LtWqB07pVefTG2HLTTSCxW6d4qimq0z6837djIDaDinc06ryCqdaU88WXJYdxmTiQfjOklebQm8HpLNjr2A8luPo1+eoFo7S1NcWCPUu7MkRPINVXgyzfAo4zXonimyDbf+M7f6QwXQxrApZjq2i7U3lERPSS4B73o9kUno7hAtYQP7oOofn2S7i4K6MXr/5k4981lDzgpq9zpPRJjl8BXyfMa/Au6BbJDkb088aIXYqKN6tzkKYj+FZS4fDx/vVbOc8Li7eVTBRgwtaDNjQRsbPXP8HcNeN8m/0Bb4os05DBPvTGmBb8+OcyBBkFZGhMWkFx0wJ8G3BO4KHegHYhvAUfIkrt+a6Dg/rRUS8o5u2sEy8/Rp3yavveE4WZwzvayeOXtY/RARIXD/nsBMh3OdV78DI5xeUTQ0SyPhAvfyTMlsamaxM4+0kR5z3f8mK4DQnfSDwUKr4v6tbfCD6uSG9C3v2QZHiRu/OM6MNe0LzK8Y9ZX+rBd/oJmEJCoC07CdZwxJfrfwPMq66+WX8n5eC9MEXXrW0sXKbBTW14yaiM6QbtN/XAfCLp54N9e0m4xtSQkONY5yIlw7xzLd83dx8IatxXEptrc9ut+Pe3Wn1fNp34StpRaiA40Cv0hyh0TbPHMZU/z5xdFvnyD/b0pRxH6xkIoyy
  template:
    metadata:
      creationTimestamp: null
      name: mastodon-smtp-auth
      namespace: mastodon
