apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: ceph-objectstore-secure
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: true
  gateway:
    sslCertificateRef: letsencrypt-wildcard-cert-henabytes.com-staging
    port: 80
    securePort: 443
    instances: 1
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
