apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ceph-objectstore-secure
  namespace: rook-ceph
spec:
  secretName: self-signed-cert-ceph-objectstore-secure
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: ""
  duration: 170000h
  renewBefore: 72h
  issuerRef:
    kind: Issuer
    name: selfsigned
  commonName: "rook-ceph-rgw-ceph-objectstore-secure.rook-ceph.svc"
  isCA: true
  dnsNames:
    - "rook-ceph-rgw-ceph-objectstore-secure.rook-ceph.svc"
