apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism-mariadb
  namespace: photoprism
spec:
  chart:
    spec:
      chart: mariadb
      version: 11.4.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 15m
  timeout: 1h
  install:
    disableWait: true
  upgrade:
    disableWait: true
  releaseName: mariadb
  valuesFrom:
    - kind: ConfigMap
      name: photoprism-mariadb-helm-chart-value-overrides
      valuesKey: values.yaml # This is the default, but best to be explicit for clarity
