apiVersion: v1
kind: ConfigMap
metadata:
  name: photoprism-helm-chart-value-overrides
  namespace: photoprism
data:
  values.yaml: |-
    #
    # IMPORTANT NOTE
    #
    # This chart inherits from our common library chart. You can check the default values/options here:
    # https://github.com/geek-cookbook/library-charts/tree/main/charts/stable/common/values.yaml
    #

    image:
      # -- image repository
      repository: photoprism/photoprism
      # -- image tag
      # @default -- chart.appVersion
      tag: 221118-jammy
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables. See [image docs](https://docs.photoprism.org/getting-started/config-options/) for more details.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: UTC
      # -- Photoprism storage path
      PHOTOPRISM_STORAGE_PATH: /photoprism/storage
      # -- Photoprism originals path
      PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
      # -- Initial admin password. **BE SURE TO CHANGE THIS!**
      - name: PHOTOPRISM_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: photoprism-secrets
            key: PHOTOPRISM_ADMIN_PASSWORD
      # -- Disable authentication / password protection
      PHOTOPRISM_PUBLIC: "false"
      # -- Sets UID Photoprism runs under.
      UID:  # 1000
      # -- Sets GID Photoprism runs under.
      GID:  # 1000
      # -- Sets UMASK.
      UMASK:  # 0000
      # -- Database driver (sqlite, mysql)
      PHOTOPRISM_DATABASE_DRIVER: mysql
      # -- Database host incl. port
      PHOTOPRISM_DATABASE_SERVER: mariadb.photoprism.svc.cluster.local:3306
      # -- Database schema name
      PHOTOPRISM_DATABASE_NAME: photoprism
      # -- Database user name
      PHOTOPRISM_DATABASE_USER: photoprism
      # -- Database user password
      - name: PHOTOPRISM_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: photoprism-secrets
            key: mariadb-password

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 2342

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        hosts:
        - host: photoprism.henabytes.com
          paths:
          - /
        tls:
        - hosts:
          - photoprism.henabytes.com
          secretName: letsencrypt-wildcard-cert-henabytes.com-staging

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: true
        storageClass: ceph-block
        mountPath: /photoprism/storage

      originals:
        enabled: true
        storageClass: ceph-block
        mountPath: /photoprism/originals

    # -- Enable and configure mariadb database subchart under this key.
    #    For more options see [mariadb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/mariadb)
    # @default -- See values.yaml
    mariadb:
      enabled: false
      architecture: standalone
      auth:
        database: photoprism
        username: photoprism
        password: photoprism
        rootPassword: photoprism
      primary:
        persistence:
          enabled: false
          # storageClass: ""
