apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: photoprism
spec:
  chart:
    spec:
      chart: photoprism
      version: 7.x
      sourceRef:
        kind: HelmRepository
        name: geek-cookbook
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: photoprism
  valuesFrom:
    - kind: ConfigMap
      name: photoprism-helm-chart-value-overrides
      valuesKey: values.yaml # This is the default, but best to be explicit for clarity
