apiVersion: v1
kind: Secret
metadata:
  name: cluster-user-auth
  namespace: flux-system
type: Opaque
data:
  password: JDJhJDEwJGouVzZ3VUg1eTJpdXpTR1BBWld0d2VUdzJnSXVEeWt3dWFLZXZLYjVIbmNJWEFYWXRIOTZ5Cg==
