apiVersion: v1
kind: ConfigMap
metadata:
  name: doplarr-helm-chart-value-overrides
  namespace: doplarr
data:
  values.yaml: |-
    image:
      repository: tccr.io/truecharts/doplarr
      tag: 3.6.2@sha256:ca3632a6f7b981c4b2231628f79d46b4a551f8fc28749ed1c93152ccd5693dc5
      pullPolicy: IfNotPresent

    envFrom:
      - secretRef:
          name: doplarr-secrets

    secretEnv:
      # OVERSEERR__API: ""
      OVERSEERR__DEFAULT_ID: ""
      SONARR__API: ""
      RADARR__API: ""
      DISCORD__ROLE_ID: ""
      # DISCORD__TOKEN: ""

    env:
      OVERSEERR__URL: overseerr.henabytes.com
      DISCORD__MAX_RESULTS: 25
      DISCORD__REQUESTED_MSG_STYLE: ":plain"
      SONARR__URL: ""
      SONARR__QUALITY_PROFILE: ""
      SONARR__LANGUAGE_PROFILE: ""
      RADARR__URL: ""
      RADARR__QUALITY_PROFILE: ""
      PARTIAL_SEASONS: true
      LOG_LEVEL: ":info"

    service:
      main:
        enabled: false
        ports:
          main:
            enabled: false

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    portal:
      enabled: false
