apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: metallb-advertisment
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-pool # (1)!
  aggregationLength: 32
  localPref: 100
  communities:
  - 65535:65282
