apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: "ceph.henabytes.com"
  namespace: rook-ceph
spec:
  endpoints:
    - dnsName: "ceph.henabytes.com"
      recordTTL: 180
      recordType: CNAME
      targets:
        - "home.henabytes.com"
