apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-dashboard
  namespace: rook-ceph
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "ceph.internal.henabytes.com"
  labels:
    app: rook-ceph-mgr
    ceph_daemon_id: b
    rook_cluster: rook-ceph
spec:
  ports:
    - name: https-dashboard
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: rook-ceph-mgr
    ceph_daemon_id: b
    rook_cluster: rook-ceph
  sessionAffinity: None
  type: LoadBalancer
