apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      chart: nextcloud
      version: 3.4.7
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  interval: 15m
  timeout: 1h
  install:
    disableWait: true
  upgrade:
    disableWait: true
  releaseName: nextcloud
  valuesFrom:
    - kind: ConfigMap
      name: nextcloud-helm-chart-value-overrides
      valuesKey: values.yaml # This is the default, but best to be explicit for clarity
