apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-redirectregex
  namespace: nextcloud
spec:
  redirectRegex:
    permanent: true
    regex: "^/.well-known/ca(l|rd)dav"
    replacement: "/remote.php/dav"
