apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb-config
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: metallb
    meta.helm.sh/release-namespace: metallb-system
data:
  config: |
    peers:
    - peer-address: 192.168.1.1
      peer-asn: 64501
      my-asn: 64500

    address-pools:
    - name: default
      protocol: bgp
      avoid-buggy-ips: true
      addresses:
      - 192.168.2.0/24
