apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: trust-manager
      version: v0.4.x
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: trust-manager
  valuesFrom:
    - kind: ConfigMap
      name: trust-manager-helm-chart-value-overrides
      valuesKey: values.yaml # This is the default, but best to be explicit for clarity
