apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgAyVbYJpcn8Uovtx9isuklV31Xe34onPUsdyC5vZso72l75LyZe9OOcR5orAs1nQxzOqq2EYLuHSDQCWwHoq8QMO5hFlY7vzBTjLnHVwh9GeKgghVvEDMZrlLlFx023hvWjjw+tKQKx7CHkseKUA2INcVA+sj6DoHyY9yEL2LnGRaQoeewXbH8xCRSZ9vndTgcATe5xsEu1Fb+FWx0E4lLIXbBnantMYj6SroQqptH7l8VSm7nufvGI22T0Oe5bCAkRyU7piz2xQoHFqqmqUqbm9h1LHOxG5abrfbnBbmlopOO5AHxbIjN90C8R7DLXCY5026Y8RtRrN6c9LlwjGyubFTjMpNKzb24limFu4dW0KwvoMqylcfiYuLxk3BAq8Iia2rt3VXY5ezu9H+uCL1b4dHohWYdJYqK7IL/NgdfMXbeKY+rTqtrnuPFw5dhp7shVDlN4/ff+OSrrCLPrMVBWu0XpLY0J/UGZ+NN0fyR3PS/xoGKCbyb3dsxgkOJiutMhSB3GMxoiOlymdspCvdxv2ZBYH+qWmwN05fN0uhgF7kisWnIa5N2fdEj322Bts30vG2w5cP5FwdjfuwGJ98qaXAt0IqoSF4EBp93m7T45vu3z1WawL0GlRMx3wCZZFAOgbEKihfOXWZmz/yETPt+/6NOqSrEp6Q3yqPG0xSFqHKHHblg1bQe7D5DQtzZkCt/OjS5fltv0nQkjuG0MwDAiTfDDtR8cOEMkcCRB1XbEhSmJCzW7TlzA
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
